version: "3.2"
services:
    rabbitmq3:
        container_name: "rabbitmq"
        image: rabbitmq:3.8-management-alpine
        environment:
            - RABBITMQ_DEFAULT_USER=rabbit
            - RABBITMQ_DEFAULT_PASS=1234
        ports:
            - '5672:5672' # AMQP protocol port
            - '15672:15672' # HTTP management UI
        volumes:
            - ./rabbitmq/data/:/var/lib/rabbitmq/
            - ./rabbitmq/log/:/var/log/rabbitmq
