version: "3.2"
services:

  backend:
    build:
      context: .
      dockerfile: backend/backend.Dockerfile
    command: python backend.py
    restart: unless-stopped
    ports:
      - 50051:50051

  ecdsa_nonce_attack:
    build:
      context: .
      dockerfile: attacks/Dockerfile
    command: python attacks/ecdsa_reused_nonce.py
    restart: unless-stopped
    depends_on:
      - backend
